services:
  - type: worker
    name: telegram-auto-reply-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python telegram_auto_reply.py
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: PHONE_NUMBER
        sync: false 